### ISSUE TITLE
Hyper Parameter Grid Search Implementation 

### ISSUE THREAD

**Issue by milesgranger** [equinor/gordo-components#246]
Tracking issue for implementation of grid search hyper parameter tuning.

- [ ] Model builder - Toggle option to not save a model (https://github.com/equinor/gordo-components/issues/244)
- [ ] Model builder - Output scoring to stdout (https://github.com/equinor/gordo-components/issues/243)
- [ ] Model builder - Ability to customize scoring (https://github.com/equinor/gordo-components/issues/242)
- [ ] Template the model config - (https://github.com/equinor/gordo-components/issues/241)
